### ISSUE TITLE
User story 

### ISSUE THREAD

**Issue by AnoukdeRooij24** [AnoukdeRooij24/fix-the-flow-interactive-website#12]
**User story:**
Als bezoeker van de website van Bieb in bloei wil ik voor Harry kunnen zorgen, zodat hij vrolijk mee kan om mij te begeleiden over de website.

**Wire flow:**
![wireflow-zorgvoorharry](https://github.com/user-attachments/assets/b0f3dd1c-6783-4238-a312-4b2bd6e8be0f)

**Comment by Sebastiaan-hva** [comment]
Idee voor design: De wolk schuift iets naar rechts (en dan misschien weer terug) on hover. 
Ik zou nog nadenken over hoe je harry zn transitie van verdrietig naar blij gaat maken. Want van de ene naar andere foto wisselen is misschien niet heel mooi. 
Je kan ook doen dat de achtergrond een iets lichtere kleur wordt als je op de wolk clickt.

**Comment by Rapha2002** [comment]
Leuk idee, feedforward kan misschien voor sommige mensen een beetje onduidelijk zijn omdat niet is aangegeven hoe je voor Harry moet zorgen dus wellicht zou een pijltje naar de wolk kunnen helpen. Feedback is duidelijk door de verdwijnende wolk en omdat hij blij wordt
