### ISSUE TITLE
Ontwerp User Interacion

### ISSUE THREAD

**Issue by AnoukdeRooij24** [AnoukdeRooij24/fix-the-flow-interactive-website#13]
![image](https://github.com/user-attachments/assets/0e30f9d6-7505-4800-8c98-47c69f8eb757)
![image](https://github.com/user-attachments/assets/51aef84a-d310-43e7-8e5a-305a4c4532fb)

**Comment by krijnhoetmer** [comment]
Maak het niet te groot, maar probeer het driestappenplan van JS hierop toe te passen.

**Comment by krijnhoetmer** [comment]
Hoe heb je dit precies opgelost? Ik zie geen gekoppelde commits, dus lastig inschatten. Probeer de issue nummers (#13 in dit geval) in je commit messages te noemen, zodat GitHub ze automatisch koppelt.
